name = "vodar-website"
main = "worker.js"
compatibility_date = "2026-09-18"

[assets]
directory = "public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "vodar-shop"
database_id = "9a96740e-ac10-4272-b5e1-4c39749a46fe"
